<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_message</name>
   <tag></tag>
   <elementGuidId>ab25f4eb-0a88-4efd-98c0-3ff65c54bbb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//i[text()='Dashboard']/following::span[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//i[text()='Dashboard']/following::span[5]</value>
   </webElementProperties>
</WebElementEntity>
